// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using PasswordVault.Infrastructure.Data;

#nullable disable

namespace PasswordVault.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PasswordVault.Domain.Entities.Account", b =>
            {
                b.Property<int>("AccountId").ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));
                b.Property<string>("AccountName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Category").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<DateTime>("CreatedDate").HasColumnType("datetime2").HasDefaultValueSql("GETDATE()");
                b.Property<string>("EncryptedOtherInfo").HasColumnType("nvarchar(max)");
                b.Property<string>("EncryptedPassword").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("EncryptionIV").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<DateTime?>("UpdatedDate").HasColumnType("datetime2");
                b.Property<int>("UserId").HasColumnType("int");
                b.Property<string>("UserName").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
                b.Property<string>("WebsiteUrl").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.HasKey("AccountId");
                b.HasIndex("UserId");
                b.ToTable("Accounts");
            });

            modelBuilder.Entity("PasswordVault.Domain.Entities.User", b =>
            {
                b.Property<int>("UserId").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));
                b.Property<DateTime>("CreatedDate").HasColumnType("datetime2").HasDefaultValueSql("GETDATE()");
                b.Property<string>("Email").IsRequired().HasMaxLength(255).HasColumnType("nvarchar(255)");
                b.Property<string>("FullName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<bool>("IsActive").HasColumnType("bit").HasDefaultValue(true);
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("PasswordSalt").IsRequired().HasColumnType("nvarchar(max)");
                b.HasKey("UserId");
                b.HasIndex("Email").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("PasswordVault.Domain.Entities.Account", b =>
            {
                b.HasOne("PasswordVault.Domain.Entities.User", "User")
                    .WithMany("Accounts")
                    .HasForeignKey("UserId")
                    .HasConstraintName("FK_Accounts_Users")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("User");
            });

            modelBuilder.Entity("PasswordVault.Domain.Entities.User", b =>
            {
                b.Navigation("Accounts");
            });
#pragma warning restore 612, 618
        }
    }
}
