-- =============================================================
-- Seed Data – Demo user for development only
-- Password: Admin@123456
-- NOTE: Replace these hashes with freshly generated ones in prod.
-- =============================================================

USE PasswordVaultDB;
GO

-- Demo user (password = "Admin@123456", PBKDF2-SHA512)
IF NOT EXISTS (SELECT 1 FROM dbo.Users WHERE Email = 'demo@passwordvault.dev')
BEGIN
    INSERT INTO dbo.Users (FullName, Email, PasswordHash, PasswordSalt, CreatedDate, IsActive)
    VALUES (
        'Demo User',
        'demo@passwordvault.dev',
        -- These are placeholder values. Real hashes are generated by the API on registration.
        'PLACEHOLDER_HASH_REPLACE_VIA_REGISTRATION',
        'PLACEHOLDER_SALT_REPLACE_VIA_REGISTRATION',
        GETDATE(),
        1
    );
    PRINT 'Demo user inserted. Register via API to get proper hashes.';
END
GO
